themeDir: themes
theme: salsa-caribe-2016
baseurl: http://www.salsacaribe.co.uk
title: Learn to dance with the cuban salsa specialists
languageCode: en
buildDraft: true
watch: true

# Dynamic menus
menu:
  main:
    - Name: Home
      Weight: -120
      URL: '/'
    - Name: 'About us'
      Weight: -110
      URL: '/about/'
    - Name: "Contact us"
      Weight: -100
      URL: '#contact'
