themeDir: themes
theme: salsa-caribe-2016
baseurl: http://www.salsacaribe.co.uk
title: Learn to dance with the cuban salsa specialists
languageCode: en
buildDraft: true
watch: true
metaDataFormat: yaml
