themeDir: themes
theme: salsa-caribe-2016
baseurl: http://www.salsacaribe.co.uk
title: Salsa Caribe
languageCode: en
metaDataFormat: yaml
buildDraft: true
watch: true

params:
  logo: Salsa Caribe _Productions_
  tagline: Learn to dance with the cuban salsa specialists

# Dynamic menus
menu:
  main:
    # - Name: Salsa Caribe
    #   weight: -160
    #   URL: /
    #   indentifier: home
    # - name: Classes & events
    #   identifier: events
    #   weight: -140
    #   URL: '/'
    # - name: Private classes
    #   identifier: private-classes
    #   Weight: -120
    #   URL: '/private-classes'
    # - name: 'About us'
    #   identifier: about
    #   weight: -110
    #   URL: '/about/'
    - name: "Contact us"
      identifier: contact
      weight: 4
      URL: '#contact'
