themeDir: themes
theme: salsa-caribe-2016
baseurl: http://www.salsacaribe.co.uk
title: Salsa Caribe
languageCode: en
buildDraft: true
watch: true

params:
  logo: Salsa Caribe
  tagline: Learn to dance with the cuban salsa specialists

# Dynamic menus
menu:
  main:
    - Name: Classes & events
      Weight: -120
      URL: '/'
    - Name: 'About us'
      Weight: -110
      URL: '/about/'
    - Name: "Contact us"
      Weight: -100
      URL: '#contact'
